server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: 1997

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: my-super-secret-key-for-gateway-256-bit-minimum
